// Generated by scripts/build-public-content.mjs. Do not edit directly.

export const PUBLIC_SOURCE_COVERAGE = {
  "version": "1.0.0",
  "asOfDate": "2026-07-17",
  "status": "engineering-integration-status-not-live-availability",
  "disclaimer": "This registry describes implemented software boundaries. It does not establish live provider health, complete court or date coverage, official reproduction, current law, or comprehensive judicial treatment.",
  "providers": [
    {
      "id": "a2aj-canada",
      "name": "A2AJ Canadian legal data",
      "jurisdictions": [
        "Canada",
        "Ontario"
      ],
      "materials": [
        "Decisions",
        "Ontario and federal legislation discovery",
        "Metadata",
        "Unofficial text where supplied"
      ],
      "authority": "Third-party aggregation; not an official reproduction",
      "integrationStatus": "Implemented; runtime health required",
      "enabledByDefault": true,
      "knownLimits": "Coverage is the dataset list reported by A2AJ at runtime. All reproductions are unofficial and require official-source checking. Court, date, language, text, and treatment coverage may be incomplete. No comprehensive noting-up claim.",
      "implementationSource": "backend/src/lib/legalSources/a2ajProvider.ts"
    },
    {
      "id": "ontario-elaws",
      "name": "Ontario e-Laws",
      "jurisdictions": [
        "Ontario"
      ],
      "materials": [
        "Statutes",
        "Regulations",
        "Rules"
      ],
      "authority": "Official display source; ROSS extraction is an unofficial reproduction",
      "integrationStatus": "Implemented; runtime health required",
      "enabledByDefault": true,
      "knownLimits": "Current-source retrieval and currency metadata are implemented. Historical-version retrieval is not enabled until an official stable interface is validated.",
      "implementationSource": "backend/src/lib/legalSources/officialLegislation.ts"
    },
    {
      "id": "justice-laws-canada",
      "name": "Justice Laws Canada",
      "jurisdictions": [
        "Canada"
      ],
      "materials": [
        "Federal statutes",
        "Federal regulations"
      ],
      "authority": "Official stable links; ROSS extraction is an unofficial reproduction",
      "integrationStatus": "Implemented; runtime health required",
      "enabledByDefault": true,
      "knownLimits": "Current XML and currency metadata are implemented. A historical answer requires an explicit archived version and cannot be inferred from the current repository.",
      "implementationSource": "backend/src/lib/legalSources/officialLegislation.ts"
    },
    {
      "id": "courtlistener-us",
      "name": "CourtListener",
      "jurisdictions": [
        "United States"
      ],
      "materials": [
        "U.S. decisions",
        "Citations",
        "Opinion text where supplied"
      ],
      "authority": "Third-party aggregation; not an official reproduction",
      "integrationStatus": "Inherited and preserved as an optional U.S. provider",
      "enabledByDefault": true,
      "knownLimits": "Not an Ontario or Canadian authority source. Coverage, opinion text, and citation verification depend on CourtListener and configured credentials.",
      "implementationSource": "backend/src/lib/legalSources/courtlistenerProvider.ts"
    },
    {
      "id": "canlii-licensed",
      "name": "CanLII licensed connector boundary",
      "jurisdictions": [
        "Canada",
        "Ontario"
      ],
      "materials": [
        "Entitlement-defined metadata or text"
      ],
      "authority": "Requires separate provider agreement and approved transport",
      "integrationStatus": "Disabled; no licence or transport approved",
      "enabledByDefault": false,
      "knownLimits": "ROSS does not scrape CanLII. No request is implemented by the connector until contract, operation, retention, redistribution, credential, and transport gates are satisfied.",
      "implementationSource": "backend/src/lib/legalSources/licensedConnector.ts"
    }
  ]
} as const;
