// Generated by scripts/build-public-content.mjs. Do not edit directly.

export const PUBLIC_BRAND_CONFIG = {
  "product": {
    "name": "ROSS",
    "expandedName": "Ranade OSS",
    "tagline": "Ontario-first legal work, built in the open.",
    "description": "A public-registration legal AI workspace in development for Ontario lawyers and paralegals.",
    "betaLabel": "Public beta — verified account required; synthetic or non-confidential materials only",
    "legalOperator": "Abhi Ranade",
    "productOwner": "Abhi Ranade",
    "technicalOwner": "AR",
    "legalContentOwner": "AR"
  },
  "urls": {
    "website": "https://ross-ontario.augustmaat.chatgpt.site",
    "app": "https://ross-ranadeoss-public.fly.dev",
    "api": "https://ross-ranadeoss-api.fly.dev",
    "status": "https://ross-ontario.augustmaat.chatgpt.site/status",
    "support": "mailto:abhi@soundmarklaw.com",
    "security": "https://github.com/ranade-oss/ROSS-RanadeOSS/security/advisories/new",
    "source": "https://github.com/ranade-oss/ROSS-RanadeOSS",
    "upstreamSource": "https://github.com/Open-Legal-Products/mike",
    "upstreamWebsite": "https://mikeoss.com"
  },
  "policy": {
    "defaultJurisdiction": "CA-ON",
    "productionDataResidencyTarget": "Canada",
    "previewData": "synthetic-only",
    "coverageStatus": "limited-source-reviewed",
    "courtListenerPreserved": true,
    "canliiScrapingAllowed": false,
    "governmentAffiliation": false,
    "trademarkReview": "TBD"
  },
  "attribution": {
    "short": "ROSS is a modified fork of Mike and is licensed under AGPL-3.0.",
    "noticePath": "NOTICE.md"
  },
  "socialLinks": []
} as const;
