// Generated by scripts/build-ross-workflows.mjs. Do not edit directly.

import type { SystemWorkflow } from "./systemWorkflows";

export const ROSS_SYSTEM_WORKFLOWS: SystemWorkflow[] = [
    {
        "user_id": null,
        "is_system": true,
        "created_at": "",
        "id": "builtin-ross-ontario-civil-claim-defence-issue-extraction",
        "metadata": {
            "title": "Ontario Civil Claim and Defence Issue Extraction",
            "description": "Extract pleaded facts, causes of action, defences, remedies, admissions, denials, and material gaps from Ontario civil pleadings.",
            "type": "assistant",
            "contributors": [
                {
                    "name": "ROSS contributors",
                    "organisation": "Ranade OSS",
                    "role": "Draft workflow author",
                    "linkedin": null
                },
                {
                    "name": "Abhi Ranade, Lawyer (LSO #90546L)",
                    "organisation": "Independent Ontario legal review",
                    "role": "Ontario workflow reviewer",
                    "linkedin": null
                }
            ],
            "language": "English",
            "version": "0.1.0",
            "practice": "Civil Litigation",
            "jurisdictions": [
                "Canada / Ontario"
            ]
        },
        "skill_md": "# Ontario Civil Claim and Defence Issue Extraction\n\n## Boundary\n\nThis draft supports an Ontario professional reviewing synthetic or non-confidential pleadings. It does not give consumer advice, amend a pleading, calculate a limitation period, or decide the merits.\n\n## Instructions\n\n1. Confirm the represented party, court, region, legal as-of date, and that the claim and defence are present. If any are missing, stop and ask for them.\n2. Extract only what the pleadings state. Cite the pleading name and paragraph for every factual finding.\n3. Build a table with: issue; claim allegation; defence response; admission, denial, or no response; pleaded legal basis; requested remedy; source location; missing information.\n4. Keep allegations, admissions, evidence, and legal conclusions separate. Do not treat silence as an admission unless retrieved current authority establishes that result for this context.\n5. Retrieve the current Rules of Civil Procedure and applicable province-wide and regional practice directions through authorized legal-source tools before stating a procedural proposition. Include an exact supporting passage and canonical URL.\n6. Mark citation, passage, currency, and treatment verification independently. Never infer noting-up from ordinary search results.\n7. End with unresolved conflicts, missing pleadings or endorsements, and questions for the supervising professional. State that a human must review the result.",
        "columns_config": null
    },
    {
        "user_id": null,
        "is_system": true,
        "created_at": "",
        "id": "builtin-ross-ontario-documentary-discovery-review",
        "metadata": {
            "title": "Ontario Documentary Discovery Review",
            "description": "Review a synthetic document set for relevance, issues, chronology, duplicates, and potential privilege flags without making privilege determinations.",
            "type": "assistant",
            "contributors": [
                {
                    "name": "ROSS contributors",
                    "organisation": "Ranade OSS",
                    "role": "Draft workflow author",
                    "linkedin": null
                },
                {
                    "name": "Abhi Ranade, Lawyer (LSO #90546L)",
                    "organisation": "Independent Ontario legal review",
                    "role": "Ontario workflow reviewer",
                    "linkedin": null
                }
            ],
            "language": "English",
            "version": "0.1.0",
            "practice": "Civil Litigation",
            "jurisdictions": [
                "Canada / Ontario"
            ]
        },
        "skill_md": "# Ontario Documentary Discovery Review\n\n## Boundary\n\nThis draft organizes a synthetic or non-confidential document set. It does not make a final relevance, privilege, production, redaction, or destruction decision.\n\n## Instructions\n\n1. Confirm the represented party, pleadings or agreed issue list, court region, legal as-of date, and review protocol. Ask for missing inputs before reviewing.\n2. Preserve the source filename, document identifier, page, date, author, recipient, and document-family relationship. Never modify an original.\n3. For each document, report: responsive issue; concise factual summary; exact source location; potential duplicate or family; confidentiality indicator; potential privilege-review flag and reason; unresolved question.\n4. Use “potential privilege-review flag,” never “privileged,” unless a supervising professional supplied that determination. Do not expose flagged substance more widely than the input scope requires.\n5. Retrieve current Rules 29.1, 30, and 30.1 and applicable practice directions before stating a procedural requirement. Provide exact passages and official links.\n6. Report gaps in numbering, missing attachments, corrupt files, uncertain dates, and conflicts. Do not invent missing content.\n7. End with counts reconciled to the supplied set and a clear human decision gate for relevance, privilege, redaction, and production.",
        "columns_config": null
    },
    {
        "user_id": null,
        "is_system": true,
        "created_at": "",
        "id": "builtin-ross-ontario-affidavit-fact-check",
        "metadata": {
            "title": "Ontario Affidavit Fact Check",
            "description": "Cross-check a draft Ontario affidavit against supplied records and identify unsupported, inconsistent, ambiguous, or hearsay-sensitive passages.",
            "type": "assistant",
            "contributors": [
                {
                    "name": "ROSS contributors",
                    "organisation": "Ranade OSS",
                    "role": "Draft workflow author",
                    "linkedin": null
                },
                {
                    "name": "Abhi Ranade, Lawyer (LSO #90546L)",
                    "organisation": "Independent Ontario legal review",
                    "role": "Ontario workflow reviewer",
                    "linkedin": null
                }
            ],
            "language": "English",
            "version": "0.1.0",
            "practice": "Civil Litigation",
            "jurisdictions": [
                "Canada / Ontario"
            ]
        },
        "skill_md": "# Ontario Affidavit Fact Check\n\n## Boundary\n\nThis draft cross-checks a synthetic or non-confidential affidavit. It does not assess credibility, invent personal knowledge, decide admissibility, or approve swearing or filing.\n\n## Instructions\n\n1. Confirm the deponent, proceeding, court region, legal as-of date, draft affidavit, supporting record set, and stated basis of knowledge.\n2. Create a paragraph-by-paragraph table with: affidavit paragraph; proposition; knowledge basis stated; supporting record and pinpoint; status (supported, partially supported, inconsistent, ambiguous, or no supplied support); explanation; follow-up question.\n3. Cite both the affidavit paragraph and record location. Absence of supplied support is not proof that a statement is false.\n4. Identify internal inconsistencies, date or name mismatches, ambiguous pronouns, missing exhibit references, and statements that appear to require information-and-belief treatment. Do not rewrite facts to cure them.\n5. Retrieve current applicable rules, the Evidence Act where relevant, and the applicable practice direction before making any procedural or evidentiary observation. Quote the exact passage and link the official source.\n6. Separate factual cross-checking from legal analysis and expose every unverified proposition.\n7. End with questions for the deponent and supervising professional and an explicit human approval requirement.",
        "columns_config": null
    },
    {
        "user_id": null,
        "is_system": true,
        "created_at": "",
        "id": "builtin-ross-ontario-factum-authority-record-cross-check",
        "metadata": {
            "title": "Ontario Factum Authority and Record Cross-Check",
            "description": "Check a draft factum's record references, quoted passages, Canadian citations, and authority support while keeping verification states separate.",
            "type": "assistant",
            "contributors": [
                {
                    "name": "ROSS contributors",
                    "organisation": "Ranade OSS",
                    "role": "Draft workflow author",
                    "linkedin": null
                },
                {
                    "name": "Abhi Ranade, Lawyer (LSO #90546L)",
                    "organisation": "Independent Ontario legal review",
                    "role": "Ontario workflow reviewer",
                    "linkedin": null
                }
            ],
            "language": "English",
            "version": "0.1.0",
            "practice": "Civil Litigation and Appeals",
            "jurisdictions": [
                "Canada / Ontario",
                "Canada / Federal"
            ]
        },
        "skill_md": "# Ontario Factum Authority and Record Cross-Check\n\n## Boundary\n\nThis draft checks a synthetic or non-confidential factum. It does not approve filing, invent a record reference, or claim that ordinary search is a citator.\n\n## Instructions\n\n1. Confirm the court, region, represented party, legal as-of date, draft factum, complete supplied record, and authority list.\n2. For each material proposition, create a matrix with: factum paragraph; proposition; record pinpoint and match status; cited authority; exact retrieved authority passage; citation verification; passage verification; currency verification; treatment verification; issue.\n3. Compare quotations character-for-character while allowing clearly identified ellipses or formatting changes. Flag altered meaning, missing context, unresolved record pinpoints, and authorities not retrieved.\n4. Retrieve sources only through authorized legal-source providers. Use official rules and current Court of Appeal or regional directions for formatting or procedural propositions.\n5. Keep citation syntax, passage support, source currency, and judicial treatment as separate states. Never upgrade treatment from an ordinary search result.\n6. If authority coverage is incomplete, say which court, period, or provider is missing. Do not substitute model memory.\n7. End with blockers for the supervising professional; do not label the factum filing-ready.",
        "columns_config": null
    },
    {
        "user_id": null,
        "is_system": true,
        "created_at": "",
        "id": "builtin-ross-ontario-small-claims-intake",
        "metadata": {
            "title": "Ontario Small Claims Claim and Defence Intake",
            "description": "Organize a synthetic Small Claims matter into parties, allegations, responses, remedies, documents, procedural questions, and missing facts.",
            "type": "assistant",
            "contributors": [
                {
                    "name": "ROSS contributors",
                    "organisation": "Ranade OSS",
                    "role": "Draft workflow author",
                    "linkedin": null
                },
                {
                    "name": "Abhi Ranade, Lawyer (LSO #90546L)",
                    "organisation": "Independent Ontario legal review",
                    "role": "Ontario workflow reviewer",
                    "linkedin": null
                }
            ],
            "language": "English",
            "version": "0.1.0",
            "practice": "Small Claims Court",
            "jurisdictions": [
                "Canada / Ontario"
            ]
        },
        "skill_md": "# Ontario Small Claims Claim and Defence Intake\n\n## Boundary\n\nThis draft organizes a synthetic or non-confidential Ontario Small Claims matter for a professional. It does not provide consumer advice, calculate a limitation period, choose a cause of action, or file a form.\n\n## Instructions\n\n1. Confirm the represented party, court location, legal as-of date, service facts, claim or defence, and supporting records. Ask for any missing core input.\n2. Extract parties and roles, allegations, responses, material dates, amounts claimed, remedies requested, supporting documents, and factual gaps. Cite every extracted item to an input location.\n3. Produce an allegation-response-evidence matrix. Keep allegations separate from evidence and identify amounts that cannot be reconciled.\n4. Retrieve the current Rules of the Small Claims Court and applicable practice direction before stating a procedural requirement. Link to the official forms catalogue; never supply a retained form as though it were current.\n5. Do not assume a monetary limit, prescribed deadline, service date, or form version. If asked to count a supported procedural period, use the transparent deadline tool and show all inputs, exclusions, warnings, and the governing-rule link.\n6. Identify potential jurisdiction, venue, service, party-name, capacity, and document-completeness questions without deciding them.\n7. End with a missing-information list and mandatory review by the supervising Ontario lawyer or paralegal acting within permitted scope.",
        "columns_config": null
    }
];

export const ROSS_SYSTEM_WORKFLOW_IDS = new Set(ROSS_SYSTEM_WORKFLOWS.map((workflow) => workflow.id));
